// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdvpn0eY5_1n424g7d8-A3SjkwziWksn4',
    appId: '1:127764857215:web:a9d3356434bfb4e97c5a4a',
    messagingSenderId: '127764857215',
    projectId: 'talex-platform',
    authDomain: 'talex-platform.firebaseapp.com',
    storageBucket: 'talex-platform.firebasestorage.app',
    measurementId: 'G-GZYV33PCTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqIFm6umkb2rr2Bjh0Rt3tZ3bnyWEAIhg',
    appId: '1:127764857215:android:c861007dafcac0547c5a4a',
    messagingSenderId: '127764857215',
    projectId: 'talex-platform',
    storageBucket: 'talex-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR9kisQSDaL1Zf0woIre_7_zapHKerS0M',
    appId: '1:127764857215:ios:34e5ecaccb1847737c5a4a',
    messagingSenderId: '127764857215',
    projectId: 'talex-platform',
    storageBucket: 'talex-platform.firebasestorage.app',
    iosClientId: '127764857215-uepte6qvt5h7c9qd7od77qrnbqpfl9b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.talexPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR9kisQSDaL1Zf0woIre_7_zapHKerS0M',
    appId: '1:127764857215:ios:34e5ecaccb1847737c5a4a',
    messagingSenderId: '127764857215',
    projectId: 'talex-platform',
    storageBucket: 'talex-platform.firebasestorage.app',
    iosClientId: '127764857215-uepte6qvt5h7c9qd7od77qrnbqpfl9b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.talexPlatform',
  );
}
