import 'package:talex_platform/features/admin/domain/entities/assessment_question.dart';

abstract final class AssessmentQuestionDefaults {
  static const pairOptions = [
    'Claramente la A',
    'Más la A que la B',
    'Ambas por igual',
    'Más la B que la A',
    'Claramente la B',
  ];
  static const frequencyOptions = [
    'Nunca',
    'Rara vez',
    'Algunas veces',
    'Con frecuencia',
    'Siempre',
  ];
  static const valuesInstruction =
      '¿Cuál de las dos frases lo describe mejor a usted?';
  static const needsInstruction =
      'Si tuviera que elegir, ¿cuál de las dos es más importante para usted en un empleo?';
  static const capabilitiesInstruction =
      'Pensando en sus trabajos o proyectos de los últimos tres años, ¿con qué frecuencia le ha ocurrido lo siguiente?';
  static const pairTimeLimitSeconds = 20;

  static String instructionFor(AssessmentFront front) => switch (front) {
    AssessmentFront.coreValues => valuesInstruction,
    AssessmentFront.needs => needsInstruction,
    AssessmentFront.capabilities => capabilitiesInstruction,
  };

  static AssessmentQuestionFormat formatFor(AssessmentFront front) =>
      front == AssessmentFront.capabilities
      ? AssessmentQuestionFormat.experience
      : AssessmentQuestionFormat.pair;

  static List<String> optionsFor(AssessmentQuestionFormat format) =>
      format == AssessmentQuestionFormat.pair ? pairOptions : frequencyOptions;

  static const all = <AssessmentQuestion>[
    AssessmentQuestion(
      code: 'V01',
      order: 1,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Estabilidad',
      dimensionB: 'Trabajo en equipo',
      instruction: valuesInstruction,
      statementA:
          'Rindo mejor cuando las prioridades se mantienen en el tiempo',
      statementB: 'Obtengo mis mejores resultados trabajando en colaboración',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V02',
      order: 2,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Orientación a resultados',
      dimensionB: 'Competitividad',
      instruction: valuesInstruction,
      statementA:
          'Prefiero que se me evalúe por lo que logro y no por las horas que dedico',
      statementB:
          'Me motiva saber cómo se compara mi desempeño con el de otros',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V03',
      order: 3,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Innovación y riesgo',
      dimensionB: 'Respeto por las personas',
      instruction: valuesInstruction,
      statementA:
          'Me motiva replantear procesos que otros ya dan por resueltos',
      statementB:
          'Me importa que las decisiones que afectan a las personas se expliquen',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V04',
      order: 4,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Atención al detalle',
      dimensionB: 'Estabilidad',
      instruction: valuesInstruction,
      statementA: 'Reviso mi trabajo con rigor antes de darlo por terminado',
      statementB: 'Me da tranquilidad contar con procedimientos claros',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V05',
      order: 5,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Competitividad',
      dimensionB: 'Orientación a resultados',
      instruction: valuesInstruction,
      statementA: 'Planteo los desacuerdos de frente',
      statementB: 'Me motivan las metas exigentes que me obligan a superarme',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V06',
      order: 6,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Innovación y riesgo',
      dimensionB: 'Atención al detalle',
      instruction: valuesInstruction,
      statementA:
          'Prefiero lanzar una primera versión y mejorarla sobre la marcha',
      statementB: 'Sustento mis decisiones en datos y análisis',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V07',
      order: 7,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Respeto por las personas',
      dimensionB: 'Trabajo en equipo',
      instruction: valuesInstruction,
      statementA: 'Valoro trabajar con personas que piensan distinto a mí',
      statementB: 'Comparto información con otras áreas aunque no me la pidan',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V08',
      order: 8,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Orientación a resultados',
      dimensionB: 'Innovación y riesgo',
      instruction: valuesInstruction,
      statementA: 'Asumo como propios los compromisos que acepto',
      statementB:
          'Asumo con naturalidad que probar algo nuevo implica equivocarse',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V09',
      order: 9,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Trabajo en equipo',
      dimensionB: 'Respeto por las personas',
      instruction: valuesInstruction,
      statementA: 'Prefiero que los logros se reconozcan al equipo',
      statementB:
          'Doy mucha importancia a que se apliquen los mismos criterios a todos',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V10',
      order: 10,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Estabilidad',
      dimensionB: 'Atención al detalle',
      instruction: valuesInstruction,
      statementA:
          'Valoro que los cambios se anuncien con tiempo y se apliquen de forma gradual',
      statementB: 'Prefiero entregar algo preciso aunque tome más tiempo',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V11',
      order: 11,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Respeto por las personas',
      dimensionB: 'Competitividad',
      instruction: valuesInstruction,
      statementA: 'Me siento a gusto cuando el trato con los jefes es cercano',
      statementB: 'Defiendo mis posiciones con firmeza',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V12',
      order: 12,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Innovación y riesgo',
      dimensionB: 'Orientación a resultados',
      instruction: valuesInstruction,
      statementA:
          'Me entusiasman las iniciativas cuyo resultado todavía es incierto',
      statementB: 'Sostengo un nivel alto de exigencia de forma constante',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V13',
      order: 13,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Trabajo en equipo',
      dimensionB: 'Competitividad',
      instruction: valuesInstruction,
      statementA: 'Ayudo a mis compañeros aunque no sea mi responsabilidad',
      statementB: 'Me estimula competir por ser el mejor del sector',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V14',
      order: 14,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Atención al detalle',
      dimensionB: 'Respeto por las personas',
      instruction: valuesInstruction,
      statementA: 'Me esfuerzo por cumplir estándares de calidad exactos',
      statementB:
          'Tomo en cuenta cómo afecta a cada persona una decisión de trabajo',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V15',
      order: 15,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Estabilidad',
      dimensionB: 'Innovación y riesgo',
      instruction: valuesInstruction,
      statementA:
          'Prefiero perfeccionar un método probado antes que reemplazarlo',
      statementB: 'Suelo proponer alternativas a la forma habitual de trabajar',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V16',
      order: 16,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Orientación a resultados',
      dimensionB: 'Atención al detalle',
      instruction: valuesInstruction,
      statementA: 'Mido mi trabajo con indicadores concretos',
      statementB:
          'Noto enseguida los errores pequeños que otros pasan por alto',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V17',
      order: 17,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Trabajo en equipo',
      dimensionB: 'Estabilidad',
      instruction: valuesInstruction,
      statementA: 'Me gusta construir las soluciones junto con otros',
      statementB: 'Trabajo con comodidad dentro de lineamientos establecidos',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V18',
      order: 18,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Competitividad',
      dimensionB: 'Atención al detalle',
      instruction: valuesInstruction,
      statementA: 'Rindo mejor bajo presión competitiva',
      statementB: 'Documento con cuidado lo que hago',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V19',
      order: 19,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Orientación a resultados',
      dimensionB: 'Trabajo en equipo',
      instruction: valuesInstruction,
      statementA:
          'Me enfoco en terminar lo que empiezo aunque surjan obstáculos',
      statementB: 'Busco acuerdos antes de avanzar',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V20',
      order: 20,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Competitividad',
      dimensionB: 'Innovación y riesgo',
      instruction: valuesInstruction,
      statementA: 'Me gusta que se reconozca públicamente a quien logra más',
      statementB: 'Me siento cómodo decidiendo con información incompleta',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V21',
      order: 21,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Respeto por las personas',
      dimensionB: 'Estabilidad',
      instruction: valuesInstruction,
      statementA: 'Valoro que se escuche a todos antes de decidir',
      statementB: 'Planifico con anticipación para reducir imprevistos',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V22',
      order: 22,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Atención al detalle',
      dimensionB: 'Trabajo en equipo',
      instruction: valuesInstruction,
      statementA: 'Me gusta entender cada detalle antes de actuar',
      statementB: 'Disfruto coordinar con personas de distintas áreas',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V23',
      order: 23,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Competitividad',
      dimensionB: 'Respeto por las personas',
      instruction: valuesInstruction,
      statementA: 'Disfruto los debates intensos sobre cómo hacer las cosas',
      statementB:
          'Me importa que los errores se traten en privado y con respeto',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V24',
      order: 24,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Estabilidad',
      dimensionB: 'Orientación a resultados',
      instruction: valuesInstruction,
      statementA:
          'Valoro saber con certeza cómo será mi trabajo dentro de un año',
      statementB:
          'Me satisface que mi aporte se refleje en resultados visibles',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V25',
      order: 25,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Atención al detalle',
      dimensionB: 'Innovación y riesgo',
      instruction: valuesInstruction,
      statementA: 'Valoro los procesos de control y verificación',
      statementB:
          'Disfruto explorar métodos que nadie usa todavía en el equipo',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V26',
      order: 26,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Estabilidad',
      dimensionB: 'Competitividad',
      instruction: valuesInstruction,
      statementA:
          'Me gusta que las decisiones importantes sigan un proceso conocido',
      statementB: 'Busco ganar las oportunidades antes que otros',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V27',
      order: 27,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Innovación y riesgo',
      dimensionB: 'Trabajo en equipo',
      instruction: valuesInstruction,
      statementA: 'Valoro los entornos donde las reglas pueden cuestionarse',
      statementB: 'Considero que el éxito del grupo pesa más que el mío',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'V28',
      order: 28,
      front: AssessmentFront.coreValues,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Respeto por las personas',
      dimensionB: 'Orientación a resultados',
      instruction: valuesInstruction,
      statementA:
          'Busco entornos donde todos reciban la misma consideración sin importar el cargo',
      statementB: 'Priorizo lo que más impacto tiene sobre el objetivo',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N01',
      order: 29,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Pago por resultados',
      dimensionB: 'Estabilidad del empleo',
      instruction: needsInstruction,
      statementA:
          'Que una parte importante de mis ingresos dependa de mis resultados',
      statementB: 'Tener certeza de continuidad laboral a mediano plazo',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N02',
      order: 30,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Relaciones con compañeros',
      dimensionB: 'Reconocimiento',
      instruction: needsInstruction,
      statementA: 'Construir relaciones cercanas con mis compañeros',
      statementB:
          'Recibir reconocimiento explícito cuando el trabajo sale bien',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N03',
      order: 31,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Crecimiento profesional',
      dimensionB: 'Carga de trabajo sostenible',
      instruction: needsInstruction,
      statementA: 'Contar con un camino claro para ascender',
      statementB: 'Tener una carga de trabajo que no invada mi vida personal',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N04',
      order: 32,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Autonomía',
      dimensionB: 'Retroalimentación',
      instruction: needsInstruction,
      statementA: 'Decidir por mi cuenta cómo organizar mi trabajo',
      statementB: 'Recibir retroalimentación frecuente de mi jefe',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N05',
      order: 33,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Claridad del rol',
      dimensionB: 'Propósito',
      instruction: needsInstruction,
      statementA: 'Saber con precisión qué se espera de mí',
      statementB: 'Que mi trabajo tenga un impacto social o ambiental visible',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N06',
      order: 34,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Formación',
      dimensionB: 'Carga de trabajo sostenible',
      instruction: needsInstruction,
      statementA: 'Acceder a formación que amplíe mis capacidades',
      statementB: 'Terminar la jornada a una hora razonable',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N07',
      order: 35,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Pago por resultados',
      dimensionB: 'Flexibilidad',
      instruction: needsInstruction,
      statementA: 'Poder ganar más cuando mi desempeño es superior',
      statementB: 'Poder ajustar mi horario según mis necesidades',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N08',
      order: 36,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Reconocimiento',
      dimensionB: 'Propósito',
      instruction: needsInstruction,
      statementA: 'Que mis aportes sean visibles para la dirección',
      statementB: 'Sentir que mi trabajo contribuye a algo más grande',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N09',
      order: 37,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Flexibilidad',
      dimensionB: 'Relaciones con compañeros',
      instruction: needsInstruction,
      statementA: 'Poder elegir desde dónde trabajo',
      statementB: 'Trabajar en un ambiente cálido y cercano',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N10',
      order: 38,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Retroalimentación',
      dimensionB: 'Formación',
      instruction: needsInstruction,
      statementA: 'Tener conversaciones periódicas sobre mi desempeño',
      statementB: 'Aprender algo nuevo de forma constante en el trabajo',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N11',
      order: 39,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Autonomía',
      dimensionB: 'Claridad del rol',
      instruction: needsInstruction,
      statementA: 'Trabajar sin supervisión cercana',
      statementB:
          'Conocer de antemano los criterios con que se evaluará mi trabajo',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'N12',
      order: 40,
      front: AssessmentFront.needs,
      format: AssessmentQuestionFormat.pair,
      dimensionA: 'Estabilidad del empleo',
      dimensionB: 'Crecimiento profesional',
      instruction: needsInstruction,
      statementA: 'Contar con un contrato y unos ingresos predecibles',
      statementB: 'Asumir más responsabilidades en poco tiempo',
      options: pairOptions,
      timeLimitSeconds: 20,
    ),
    AssessmentQuestion(
      code: 'C01',
      order: 41,
      front: AssessmentFront.capabilities,
      format: AssessmentQuestionFormat.experience,
      dimensionA: 'Conocimiento técnico',
      instruction: capabilitiesInstruction,
      statementA:
          'He resuelto problemas técnicos de mi área sin necesitar el apoyo de un especialista',
      options: frequencyOptions,
    ),
    AssessmentQuestion(
      code: 'C02',
      order: 42,
      front: AssessmentFront.capabilities,
      format: AssessmentQuestionFormat.experience,
      dimensionA: 'Experiencia comparable',
      instruction: capabilitiesInstruction,
      statementA:
          'He desempeñado funciones muy similares a las que exige este cargo',
      options: frequencyOptions,
    ),
    AssessmentQuestion(
      code: 'C03',
      order: 43,
      front: AssessmentFront.capabilities,
      format: AssessmentQuestionFormat.experience,
      dimensionA: 'Ritmo y volumen',
      instruction: capabilitiesInstruction,
      statementA:
          'He sostenido periodos de trabajo intenso durante semanas sin bajar la calidad',
      options: frequencyOptions,
    ),
    AssessmentQuestion(
      code: 'C04',
      order: 44,
      front: AssessmentFront.capabilities,
      format: AssessmentQuestionFormat.experience,
      dimensionA: 'Complejidad analítica',
      instruction: capabilitiesInstruction,
      statementA:
          'He analizado problemas con muchas variables y he llegado a una solución clara',
      options: frequencyOptions,
    ),
    AssessmentQuestion(
      code: 'C05',
      order: 45,
      front: AssessmentFront.capabilities,
      format: AssessmentQuestionFormat.experience,
      dimensionA: 'Comunicación',
      instruction: capabilitiesInstruction,
      statementA:
          'He explicado ideas complejas de forma que personas de otras áreas las entiendan',
      options: frequencyOptions,
    ),
    AssessmentQuestion(
      code: 'C06',
      order: 46,
      front: AssessmentFront.capabilities,
      format: AssessmentQuestionFormat.experience,
      dimensionA: 'Coordinación',
      instruction: capabilitiesInstruction,
      statementA:
          'He coordinado trabajo con áreas o proveedores sobre los que no tenía autoridad directa',
      options: frequencyOptions,
    ),
    AssessmentQuestion(
      code: 'C07',
      order: 47,
      front: AssessmentFront.capabilities,
      format: AssessmentQuestionFormat.experience,
      dimensionA: 'Exigencias físicas o de desplazamiento',
      instruction: capabilitiesInstruction,
      statementA:
          'He cumplido con desplazamientos o exigencias físicas similares a las de este cargo',
      options: frequencyOptions,
    ),
    AssessmentQuestion(
      code: 'C08',
      order: 48,
      front: AssessmentFront.capabilities,
      format: AssessmentQuestionFormat.experience,
      dimensionA: 'Herramientas e idiomas',
      instruction: capabilitiesInstruction,
      statementA:
          'He usado en el día a día las herramientas o idiomas que requiere este cargo',
      options: frequencyOptions,
    ),
  ];
}
